In [1]:
import numpy as np;
from numpy import *;
import scipy as sci;
import scipy.linalg as la;
import matplotlib as mpl;
import matplotlib.pyplot as plt;
import sympy as sym;

In [78]:
D = array([(0,0),(0,8),(5.5,1.58),(5.5,8),(6,8),(6,0),(0.5,6.42),(0.5,0)])

In [79]:
plt.fill(D.T[0],D.T[1],'r')

In [27]:
plt.axis([-30,30,-30,30])

[-30, 30, -30, 30]

In [84]:
import scipy.io

In [88]:
A = np.loadtxt("ps1_data.txt")

In [90]:
(LU,p) = lup_decomp(A)

In [127]:
(LU_,p_) = la.lu_factor(A)

In [109]:
    b1 = array([2,3,-1,5,7])
    b2 = array([15,29,8,4,-49])
    b3 = array([8,-11,3,-8,-32])

In [176]:
assert(1)

In [177]:
np.allclose(la.lu_solve((LU,p_),b1),lup_solve(LU,p,b1))

True

In [244]:
B = array([[4,-1,0,-1,30],[-1,4,-1,0,60],[0,-1,4,-1,70],[-1,0,-1,4,40]],dtype=float)

In [245]:
B

array([[  4.,  -1.,   0.,  -1.,  30.],
       [ -1.,   4.,  -1.,   0.,  60.],
       [  0.,  -1.,   4.,  -1.,  70.],
       [ -1.,   0.,  -1.,   4.,  40.]])

In [220]:
x = array([1,2,3,4])

In [237]:
C = B.copy()

In [246]:
C = B.copy()
C[[3,0]] = C[[0,3]];
C[[2,1]] = C[[1,2]]
C[2]-=C[0]
C[2]+=4*C[1]
C[3] += 4*C[0]
C[3] -= C[1]
C[3] += 0.5*C[2]


array([[  -1.,    0.,   -1.,    4.,   40.],
       [   0.,   -1.,    4.,   -1.,   70.],
       [   0.,    0.,   16.,   -8.,  300.],
       [   0.,    0.,    0.,   12.,  270.]])

In [252]:
A = C.copy()
(n,m) = A.shape
b = array([40,70,300,270])
x = zeros(4)
for i in range(n-1,-1,-1):
    sum = reduce(op.add,map(lambda j: C[i,j]*x[j],range(i+1,n)),0)
    x[i] = (b[i]-sum)/A[i,i]
x

array([ 20. ,  27.5,  30. ,  22.5])

In [255]:
import numpy as np;
import operator as op;
from functools import reduce;
A = array([[4,-1,0,-1,30],[-1,4,-1,0,60],
           [0,-1,4,-1,70],[-1,0,-1,4,40]],dtype=float)
A[[3,0]] = A[[0,3]]
A[[2,1]] = A[[1,2]]
A[2]-=A[0]
A[2]+=4*A[1]
A[3] += 4*A[0]
A[3] -= A[1]
A[3] += 0.5*A[2]
print(A)
b = A[:,4]
x = np.zeros(4)
for i in range(n-1,-1,-1):
    sum = reduce(op.add,map(lambda j: C[i,j]*x[j],range(i+1,n)),0)
    x[i] = (b[i]-sum)/A[i,i]
print(x)

[[  -1.    0.   -1.    4.   40.]
 [   0.   -1.    4.   -1.   70.]
 [   0.    0.   16.   -8.  300.]
 [   0.    0.    0.   12.  270.]]
[ 20.   27.5  30.   22.5]


In [265]:
do_problem_5("ps1_data.txt")

Problem 5:
LUP decomposition
L =
[[ 1.      , 0.      , 0.      , 0.      , 0.      ],
 [-0.      , 1.      , 0.      , 0.      , 0.      ],
 [-0.333333, 0.166667, 1.      , 0.      , 0.      ],
 [ 0.666667,-0.833333,-0.5     , 1.      , 0.      ],
 [-0.333333, 0.166667, 0.25    , 0.5     , 1.      ]]
U =
[[ -3.      ,  6.      ,-14.      ,-36.      , -2.      ],
 [  0.      , -6.      ,  4.      ,  6.      ,  0.      ],
 [  0.      ,  0.      , -1.333333, -5.      , -2.666667],
 [  0.      ,  0.      ,  0.      ,  0.5     ,  2.      ],
 [  0.      ,  0.      ,  0.      ,  0.      , -1.      ]]
P =
[[ 0., 0., 0., 0., 1.],
 [ 0., 0., 0., 1., 0.],
 [ 0., 0., 1., 0., 0.],
 [ 0., 1., 0., 0., 0.],
 [ 1., 0., 0., 0., 0.]]
Solving Ax = b for various values of b
b1 =
[ 2., 3.,-1., 5., 7.]
x1 =
[ 19.      ,-18.666667,-47.      , 13.5     , -2.      ]
b2 =
[ 15., 29.,  8.,  4.,-49.]
x2 =
[ 175.      , -37.666667, -57.      ,   1.      ,  30.      ]
b3 =
[  8.,-11.,  3., -8.,-32.]
x3 =
[ 0., 3., 

In [266]:
tmp = array([[1,8,1],[5,2,3],[2,4,4]])/10

In [288]:
import sympy as sym
from sympy.abc import x,y,z
from sympy import *

In [320]:
A = Matrix([[.1,.8,.1],[.5,.2,.3],[.2,.4,.4]])
D = Matrix([[.8,-.9,-10],[-.8,.3,-50],[.4,.4,80]])
E = Matrix([[.8,-.9],[-.8,.3],[.4,.4]])
F = Matrix([-10,-50,80])
B = Matrix([[.1,.8,.1,x],[.5,.2,.3,y],[.2,.4,.4,100]])
C = array([[.1,.8,.1],[.5,.2,.3],[.2,.4,.4]])

In [321]:
solve_linear_system(D,x,y)

{y: 100.000000000000, x: 100.000000000000}

In [322]:
E.solve_least_squares(F)

Matrix([
[100.0],
[100.0]])

In [323]:
(solve(0.4*x + 2.8*y - 220.0,x,y),
 solve(  1.4*x - 0.2*y - 20.0,x,y),
 solve(-1.6*x - 1.2*y + 380.0,x,y))

([{x: -7.0*y + 550.0}],
 [{x: 0.142857142857143*y + 14.2857142857143}],
 [{x: -0.75*y + 237.5}])

In [0]:
from numpy import *

In [0]:
plt.close()